''' Euler 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''
import numpy as np

def fibonacci(x):
    all_data = []
    data = []

    for i in range(x):
        if len(data) < 2:
            data.append(i)
        else:
            new = sum(data)
            data.append(new)
            all_data.append(new)
            data = data[1:]

    return all_data


print(fibonacci(4000000))
     
