''' Euler 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''
import numpy as np

def fibonacci(x):
    n = np.arange(x+1)[1:]
    for i in range(x-2):
        n[i+2] = n[i] + n[i+1]
    return n

f = fibonacci(100)
u = f[(f > 0) & (f <= 4000000)]
even = u[u % 2 == 0]

total = np.sum(even)

# 4613732
print(total)
